[package]
name = "modbus-mqtt-bridge-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
defmt = { version = "1.0", optional = true }
futures = { version = "0.3.31", default-features = false, features = ["async-await"] }
rust-mqtt = { version = "0.3.0", default-features = false }
rmodbus = { version = "0.10.2", features = ["heapless"], default-features = false }
rand_core = "0.6.4"
thiserror = { version = "2" }
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
heapless = "0.8.0"
embedded-io-async = { version = "0.6.1", optional = true }

embassy-time = { version = "0.4.0", default-features = false, optional = true }
log = { version = "0.4.27", optional = true }
tokio = { version = "1", features = ["time", "io-util"], optional = true }

[features]
default = ["std", "tokio", "embedded-io-async"]
embedded-io-async = ["dep:embedded-io-async"]
embassy = ["embedded-io-async"]
defmt = ["dep:defmt", "embedded-io-async?/defmt-03", "rust-mqtt/defmt", "embassy-time/defmt", "embassy-time/defmt-timestamp-uptime", "rust-mqtt/no_std"]
std = ["log", "embassy-time/std", "embassy-time/log",  "rust-mqtt/default"]
tokio = ["dep:tokio"]
